export function quesSet(){
	return[
  "Differentiate between UNIX and Windows based operating systems.",
  "What is a priority interrupt technique? Explain Daisy chaining method and its working.",
  "Explain different roles of operating system in brief.",
  "Explain hand shaking method of Asynchronous data transfer.",
  "What is the Distributed Operating System? Explain the advantages of distributed operating system.",
  "What is cache memory? Explain associate mapping technique.",
  "Minimize the following expression using K-map.",
  "What is the difference between process and a thread? Describe some benefits of threads.",
  "Describe how system call works.",
  "Explain following system calls: fork, ioctl, chmod, sleep.",
  "Describe the functionality of following commands in context of vi text editor: cat, more, head, grep, tail, less.",
  "Explain Paging.",
  "Explain Segmentation.",
  "Explain Demand Paging.",
  "Explain Thrashing.",
  "Explain Swapping.",
  "Explain Deadlock.",
  "Explain Inter process communication.",
  "Explain Mutual Exclusion.",
  "Explain Critical Section.",
  "Explain Spooling.",
  "Explain Buffering.",
  "Discuss various types of memory (RAM, ROM, Cache Memory, Virtual Memory).",
  "What is direct memory access (DMA)? Explain DMA controller with its block diagram.",
  "Differentiate between RISC and CISC architectures.",
  "What are the various types of addressing modes? Explain with example.",
  "Explain instruction set architecture (ISA).",
  "What is the function of registers? Discuss various types of registers used in basic computer.",
  "Explain the interrupt service routine (ISR).",
  "What are the device types of Unix Devices? Give example of each.",
  "What is the role of window manager in Unix GUI?",
  "Write the format for /etc/shadow file, explain each column.",
  "Discuss TCP/IP protocol suite. How TCP/IP is different from OSI suite?",
  "How to set system date and time from the shell prompt?",
  "Explain the following commands: mv, curl, wc, more, rmdir, grep.",
  "Explain usage of sed and some basic options of it.",
  "What is the root account in Linux and how does it differ from a normal user account?",
  "Why we need partitions in Linux? Explain Root Partition and Swap Partition.",
  "Discuss about various basic file permissions like permission.",
  "Explain the process of redirecting output to a file.",
  "Discuss the FIFO page replacement algorithms used in OS. What is Belady’s anomaly?",
  "What do you understand by Opcode and operand in Addressing mode?",
  "What is an Orphan process?",
  "What is a Daemon process?",
  "What is a Zombie process?",
  "Explain File Permissions in Linux.",
  "What is the function of the 'locate' command in Linux?",
  "What is Piping (using '|') in Linux?",
  "What is Context Switching in an operating system?",
  "What is the significance of the Program Counter (PC) register?",
  "What is the primary characteristic of Multitasking Operating Systems?",
  "What is the main purpose of Disk Formatting?",
  "How do Programmed I/O operations typically work?",
  "What is the primary function of the 'cd' command in Linux?",
  "What does 'Volatile Memory' mean?",
  "What is the difference between a 'Command Interpreter' and a 'Shell' in UNIX?",
  "What is 'Buffering' in the context of I/O operations?",
  "What is the main characteristic of 'Batch Operating Systems'?",
  "What is the significance of the 'Interrupt Priority' system?",
  "What is the purpose of 'Relative Addressing Mode'?",
  "What is the primary role of the 'Processor Status Register' (PSR) or 'Flags Register'?",
  "What is a 'File System' in an operating system?",
  "What is the main function of 'Registers' in a CPU?",
  "What is 'Memory Compaction' (or Defragmentation)?",
  "What is the 'fetch-decode-execute cycle' (Instruction Cycle)?",
  "What is the primary role of the 'Interrupt Controller' hardware?",
  "What is 'Segmentation Fault' (Segfault)?",
  "What is 'System Monitoring' in operating systems?",
  "What is the purpose of the 'head' command in Linux?",
  "What is the primary role of the 'Arithmetic Logic Unit (ALU)' in a CPU?",
  "What is 'Firmware'?",
  "What is the purpose of 'Relative Paths' in the Linux file system?",
  "What is the primary role of the '/home' directory in a Linux file system?",
  "What is the purpose of the 'sleep' system call?",
  "What is the primary advantage of 'Memory-Mapped I/O' over 'Isolated I/O'?",
  "What is the function of the 'Less' command in Linux?",
  "What are 'File Permissions' in Linux?",
  "What is the purpose of 'Microprogramming' in CPU control unit design?",
  "Which of the following is an example of an 'Open Source Software'?",
  "What is the primary function of the 'fork' system call?",
  "What is the main role of the 'BIOS' (Basic Input/Output System) during computer startup?",
  "What is the significance of the 'Sticky Bit' permission in Linux directories?",
  "What is the key difference between 'Absolute Path' and 'Relative Path' in Linux?",
  "What is the role of 'Device Drivers' in an operating system?",
  "What is 'Bus Arbitration' in computer systems?",
  "Which of the following is a common method for 'Parallel Interrupt' handling?",
  "What is the purpose of 'Two-Factor Authentication (2FA)' in system security?",
  "What is 'Clock Rate' in the context of CPU performance?",
  "What is the significance of the 'execute' permission for a directory in Linux?",
  "What is 'Cache Coherence' in multiprocessor systems?",
  "What is the function of the 'ls -R' command in Linux?",
  "What are 'Instruction Set Architectures (ISA)'?",
  "What is the primary purpose of 'Time-Sharing Operating Systems'?",
  "What is 'Dirty Bit' in page tables?",
  "What is the function of the 'chown' command in Linux?",
  "What is the 'Effective Address' in computer architecture?",
  "What is a 'Transistor' in digital electronics?",
  "What is the purpose of the 'Control Unit' within the CPU?",
  "What is the primary characteristic of 'Multiprogramming Operating Systems'?",
  "What is the significance of the 'S-R Flip Flop'?",




  "What is the 'Arithmetic Logic Unit (ALU)' responsible for in a CPU?",
  "What is the purpose of 'Bootstrapping' a computer?",
  "What is 'Memory Protection' in operating systems?",
  "What is the significance of the '/proc' file system in Linux?",
  "What is 'External Fragmentation' in memory management?",
  "What is 'Internal Fragmentation' in memory management?",
  "What is the 'Truth Table' for a logic gate?",
  "What is 'Direct Addressing Mode'?",
  "What is the main purpose of 'Virtual Memory'?",
  "What is the 'Bus' in computer architecture?",
  "Which of the following is a key feature of 'Real-Time Operating Systems' (RTOS)?",
  "What is 'Demand Paging'?",
  "What is 'Spooling' in operating systems?",
  "What is the main characteristic of 'CISCs' (Complex Instruction Set Computers)?",
  "What is the purpose of 'Binary Coded Decimal (BCD)'?",
  "What is 'Memory Interleaving'?",
  "Which of the following is true about 'Microprogrammed Control Unit'?",
  "What is 'Thrashing' in an operating system?",
  "What is the primary role of the 'Program Counter' in a CPU's execution cycle?",
  "What is the difference between 'User Mode' and 'Kernel Mode' in an operating system?",
  "What is the significance of 'Root Partition' in Linux?",
  "What is the purpose of 'Swap Partition' in Linux?",
  "What is 'Memory-Mapped I/O'?",
  "What is the role of 'Cache Memory' in a computer system?",
  "What are 'System Libraries' in the context of Linux?",
  "What is 'Asynchronous data transfer' characterized by?",
  "What is the main function of the 'Boot Loader' in Linux?",
  "Which of the following is true about 'Hard Links' in Linux?",
  "What is 'Pipeline Processing' in computer architecture?",
  "What are 'Instruction Formats' in computer architecture?",
  "What is the primary role of the 'Kernel' in a Linux operating system?",
  "Which Linux command is used to display the end of a file?",
  "What is the function of the 'curl' command in Linux?",
  "Which Linux command is used to set the system date and time?",
  "What is the significance of the '/etc/shadow' file in Linux?",
  "What is the purpose of the 'mv' command in Linux?",
  "What is the function of the 'wc' command in Linux?",
  "What is the function of the 'rmdir' command in Linux?",
  "What is the function of the 'grep' command (in vi context)?",
  "What is the function of the 'cat' command (in vi context)?",
  "What is the function of the 'more' command (in vi context)?",
  "What is the function of the 'head' command (in vi context)?",
  "What is the function of the 'tail' command (in vi context)?",
  "What is the function of the 'less' command (in vi context)?",
  "Explain Interrupt service routine (ISR).",
  "Explain the process of redirecting output to a file.",
  "Discuss about various basic file permissions.",
  "What is Belady’s anomaly in page replacement algorithms?",
  "What is an Opcode in Addressing mode?",
  "What is an Operand in Addressing mode?",
  "Explain the difference between a process and a thread.",
  "Describe the various types of registers used in a basic computer.",
  "What is the significance of the Program Counter (PC) register?",
  "What is the purpose of the Memory Address Register (MAR)?",
  "What is the role of the Instruction Register (IR)?",
  "What is the function of the Processor Status Register (PSR) or Flags Register?",
  "Explain the concept of Direct Memory Access (DMA).",
  "Describe the purpose of the DMA controller.",
  "What is Memory Interleaving and why is it used?",
  "Explain the function of the Bus in computer architecture.",
  "What is Bus Arbitration?",
  "Describe the steps involved in the fetch-decode-execute cycle.",
  "What is a Microprogrammed Control Unit?",
  "Explain the concept of Instruction Formats.",
  "What are Instruction Set Architectures (ISA)?",
  "How does Pipeline Processing improve CPU performance?",
  "What are the characteristics of CISC (Complex Instruction Set Computer) architectures?",
  "What is the primary characteristic of RISC (Reduced Instruction Set Computer) architectures?",
  "Explain the purpose of a Karnaugh Map (K-map) in digital logic design.",
  "What is a Truth Table for a logic gate?",
  "What is a Transistor and its role in digital electronics?",
  "What is the purpose of a S-R Flip Flop?",
  "What is Binary Coded Decimal (BCD)?",
  "What is the role of a Control Unit in a CPU?",
  "Explain the purpose of Bootstrapping a computer.",
  "What is the function of the Boot Loader in Linux?",
  "What is the main role of the BIOS during computer startup?",
  "What is a File System?",
  "What is Disk Formatting?",
  "What is the significance of the Root Partition in Linux?",
  "What is the purpose of a Swap Partition in Linux?",
  "Explain the primary role of the Kernel in a Linux operating system.",
  "What is the significance of the '/proc' file system in Linux?",
  "What is a Zombie Process in UNIX?",
  "What is an Orphan Process in UNIX?",
  "What is a Daemon Process in UNIX?",
  "What are System Libraries in Linux?",
  "What is the difference between User Mode and Kernel Mode?",
  "What is Memory Protection in operating systems?",
  "Explain the concept of Virtual Memory.",
  "What is External Fragmentation in memory management?",
  "What is Internal Fragmentation in memory management?",
  "What is Memory Compaction (or Defragmentation)?",
  "What is a Page Fault in virtual memory?",
  "Explain the FIFO page replacement algorithm.",
  "What is Belady’s anomaly?",
  "What is Spooling in operating systems?",
  "What is Buffering in the context of I/O operations?",
  "What is System Monitoring in operating systems?",
  "Explain the purpose of Two-Factor Authentication (2FA) in system security.",

  "What are the different types of registers used in a basic computer and discuss their functions?",
  "What is the difference between a process and a thread?",
  "Describe some benefits of threads.",
  "Describe how system calls work.",
  "Explain the 'fork' system call.",
  "Explain the 'ioctl' system call.",
  "Explain the 'chmod' system call.",
  "Explain the 'sleep' system call.",
  "Describe the functionality of the 'cat' command in the context of the vi text editor.",
  "Describe the functionality of the 'more' command in the context of the vi text editor.",
  "Describe the functionality of the 'head' command in the context of the vi text editor.",
  "Describe the functionality of the 'grep' command in the context of the vi text editor.",
  "Describe the functionality of the 'tail' command in the context of the vi text editor.",
  "Describe the functionality of the 'less' command in the context of the vi text editor.",
  "What is Paging in operating systems?",
  "What is Segmentation in operating systems?",
  "What is Demand Paging?",
  "What is Thrashing?",
  "What is Swapping?",
  "What is Deadlock?",
  "What is Inter Process Communication?",
  "What is Mutual Exclusion?",
  "What is a Critical Section?",
  "What is Spooling?",
  "What is Buffering?",
  "Discuss the various types of memory, including RAM, ROM, Cache Memory, and Virtual Memory.",
  "What is Direct Memory Access (DMA)?",
  "Explain the DMA controller with its block diagram.",
  "Differentiate between RISC and CISC architectures.",
  "What are the various types of addressing modes?",
  "Explain different addressing modes with examples.",
  "Explain Instruction Set Architecture (ISA).",
  "What is the function of registers?",
  "Discuss various types of registers used in a basic computer.",
  "What is an Interrupt Service Routine (ISR)?",
  "What are the device types of Unix Devices? Give an example of each.",
  "What is the role of the window manager in Unix GUI?",
  "Write the format for the /etc/shadow file and explain each column.",
  "Discuss the TCP/IP protocol suite.",
  "How is TCP/IP different from the OSI suite?",
  "How to set the system date and time from the shell prompt?",
  "Explain the 'mv' command.",
  "Explain the 'curl' command.",
  "Explain the 'wc' command.",
  "Explain the 'rmdir' command.",
  "Explain the 'grep' command.",
  "Explain the usage of 'sed' and some of its basic options.",
  "Why do we need partitions in Linux? Explain Root Partition and Swap Partition.",
  "Explain the process of redirecting output to a file.",
  "In the context of Linux OS, discuss various basic file permissions.",
  "How does a Priority Interrupt technique function?",
  "Explain the Daisy Chaining method for interrupts.",
  "How is Associate Mapping Technique used with cache memory?",
  "What is the purpose of the 'Opcode' in addressing mode?",
  "What is the purpose of the 'Operand' in addressing mode?",
  "How do the different addressing modes determine the effective address?",
  "What is the significance of the Instruction Set Architecture (ISA)?",
  "How does the Control Unit generate control signals for instruction execution?",
  "Explain the concept of 'Clock Rate' in CPU performance.",
  "Describe how data is transferred in 'Asynchronous Data Transfer' using the handshaking method.",
  "What is the function of the Memory Address Register (MAR)?",
  "What is the purpose of the Instruction Register (IR)?",
  "What information is typically stored in the Processor Status Register (PSR) or Flags Register?",
  "How does Direct Memory Access (DMA) reduce CPU overhead?",
  "What are the key distinctions in the design philosophies of RISC and CISC architectures?",
  "How does a Karnaugh Map (K-map) aid in minimizing Boolean expressions?",
  "Explain the function of a Transistor as a switching device.",
  "How does a S-R Flip Flop store a bit of information?",
  "When is Binary Coded Decimal (BCD) typically used and what is its purpose?",
  "What is the role of the 'Bus' system in a computer's data transfer?",
  "Why is 'Bus Arbitration' necessary in computer systems?",
  "What is 'Memory Interleaving' and its benefit?",
  "How does 'Pipeline Processing' enhance CPU throughput?",
  "What are the main characteristics of 'Volatile Memory'?",
  "What is 'Firmware' and where is it typically stored?",
  "What is the purpose of 'Bootstrapping' a computer system?",
  "How does 'Memory Protection' prevent unauthorized memory access?",
  "What is the difference between 'External Fragmentation' and 'Internal Fragmentation'?",
  "How does 'Memory Compaction' address external fragmentation?",
  "What causes a 'Page Fault' in a virtual memory system?",
  "What is the function of the 'Dirty Bit' in page tables?",
  "Why is 'Virtual Memory' used in operating systems?",
  "How does 'Direct Addressing Mode' work?",
  "How does 'Relative Addressing Mode' calculate the effective address?",
  "What is the 'Effective Address' in computer architecture?",
  "What is the difference in how I/O devices are accessed in 'Memory-Mapped I/O' versus 'Isolated I/O'?",
  "What is 'Programmed I/O' and what is its main disadvantage?",
  "What is the role of an 'Interrupt Controller' in handling multiple interrupt requests?",
  "What is 'Cache Coherence' in multiprocessor systems?",
  "Explain the role of the 'Control Unit' in executing instructions.",
  "What is the difference between RAM and ROM based on volatility and read/write capabilities?",
  "What is 'Spooling' in the context of output devices like printers?",
  "How does 'Buffering' improve data transfer efficiency?",
  "What are 'System Libraries' and how do they benefit applications?",
  "What is the purpose of the DMA controller's block diagram?",
  "What is 'Binary Coded Decimal (BCD)' used for in data conversion?",
  "What is the primary role of the Program Counter (PC) in the CPU's execution cycle?",
  "Explain the distinction between 'User Mode' and 'Kernel Mode' in an operating system.",
  "What are the responsibilities of the Operating System Kernel?",
  "How do System Calls provide an interface between user programs and the operating system kernel?",
  "Explain the process of converting a decimal number to its binary equivalent.",
  "Describe the method for converting a binary number to its decimal equivalent.",
  "How is hexadecimal-to-binary conversion performed?",
  "What are the steps to convert an octal number to its binary representation?",
  "Explain the concept of signed magnitude representation for negative numbers.",
  "How is 1's complement used to represent negative numbers?",
  "Describe the 2's complement representation method for signed integers.",
  "Why is 2's complement preferred over 1's complement in digital systems?",
  "Explain floating-point representation using the IEEE 754 standard.",
  "What is the difference between single-precision and double-precision floating-point numbers?",
  "How does ASCII encode characters?",
  "What is Unicode, and why was it developed?",
  "Explain the difference between combinational and sequential logic circuits.",
  "State De Morgan's laws and provide an example of their application.",
  "What is the purpose of Boolean algebra in computer organization?",
  "Explain the concept of a half-adder circuit.",
  "Describe the functionality of a full-adder circuit.",
  "What is a multiplexer (MUX) and how does it work?",
  "What is a demultiplexer (DEMUX) and its application?",
  "Explain the operation of an encoder circuit.",
  "Describe the function of a decoder circuit.",
  "What is a register in terms of digital logic and its basic components?",
  "Explain the concept of a shift register.",
  "What is a counter circuit and its types?",
  "Describe the characteristics of synchronous counters.",
  "How do asynchronous counters (ripple counters) operate?",
  "What is the principle of operation of a D flip-flop?",
  "Explain the behavior of a T flip-flop.",
  "What are the control signals typically associated with a CPU?",
  "Describe the structure and function of the Data Path in a CPU.",
  "What is the role of the Microprogram Counter (MPC) in a microprogrammed control unit?",
  "Explain the concept of micro-operations.",
  "What is the difference between horizontal and vertical microprogramming?",
  "How is instruction pipelining implemented in a CPU?",
  "What are pipeline hazards, and how are they resolved?",
  "Explain the concept of data hazards in pipelining.",
  "Describe control hazards in pipelining and mitigation techniques.",
  "What is the purpose of a memory hierarchy in computer architecture?",
  "Explain the concept of locality of reference.",
  "What is 'write-through' cache policy?",
  "What is 'write-back' cache policy?",
  "Differentiate between temporal locality and spatial locality.",
  "What is the role of a write buffer in cache memory systems?",
  "Explain how virtual memory is implemented using paging.",
  "What is a Translation Lookaside Buffer (TLB) and its purpose?",
  "How does memory management unit (MMU) facilitate virtual memory?",
  "What are the main components of a typical I/O interface?",
  "Explain the difference between a synchronous and an asynchronous bus.",
  "Describe the function of a Bus Request and Bus Grant line in bus arbitration.",
  "What is the purpose of an Interrupt Vector Table?",
  "How do you convert a binary number with a fractional part to its decimal equivalent?",
  "Explain the process of converting a decimal fraction to its binary equivalent.",
  "Describe how to perform addition in binary number system.",
  "How is binary subtraction performed using 2's complement?",
  "Explain the process of binary multiplication.",
  "How do you perform binary division?",
  "What is the significance of positional notation in number systems?",
  "Explain the concept of 'radix' or 'base' in a number system.",
  "How do you convert a decimal number to any other base (e.g., base 7)?",
  "Describe the conversion from a number in an arbitrary base to decimal.",
  "What is an octal number system, and how is it related to binary?",
  "What is a hexadecimal number system, and why is it commonly used in computing?",
  "Explain how BCD (Binary Coded Decimal) represents decimal digits.",
  "What are the advantages and disadvantages of using BCD?",
  "How does Gray Code differ from Binary Code, and where is it useful?",
  "Explain the concept of error detection using parity bits.",
  "How does a Hamming Code work for error correction?",
  "What is the Von Neumann architecture?",
  "What is the Harvard architecture?",
  "Compare and contrast Von Neumann and Harvard architectures.",
  "Explain the concept of pipelining in CPU architecture.",
  "Describe different types of pipeline hazards.",
  "What is a 'superscalar' processor?",
  "Explain the concept of 'out-of-order execution'.",
  "What is the purpose of branch prediction in modern CPUs?",
  "How does speculative execution work?",
  "What is a 'register file' in CPU architecture?",
  "Explain the role of the 'Memory Management Unit' (MMU).",
  "How does a Translation Lookaside Buffer (TLB) improve performance in virtual memory systems?",
  "What are the different types of cache mapping techniques?",
  "Explain 'direct-mapped cache'.",
  "Describe 'fully associative cache'.",
  "How does 'set-associative cache' work?",
  "What are the different cache write policies?",
  "Explain 'write-through' cache policy.",
  "Explain 'write-back' cache policy.",
  "What is a 'cache hit' and a 'cache miss'?",
  "How is 'cache coherence' maintained in a multiprocessor system?",
  "Explain the 'MESI protocol' for cache coherence.",
  "What is the function of a 'control store' in a microprogrammed control unit?",
  "Describe the concept of 'micro-operations' in CPU control.",
  "What is the difference between 'horizontal' and 'vertical' microprogramming?",
  "Explain the difference between 'synchronous' and 'asynchronous' data transfer.",
  "What is 'handshaking' in asynchronous data transfer?",
  "Describe the operation of a 'bus arbitration scheme'.",
  "What is the purpose of 'Interrupts' in computer systems?",
  "Explain the role of the 'Interrupt Vector Table'.",
  "What is 'Polling' as an I/O technique, and its drawbacks?",
  "Explain the concept of 'programmed I/O' versus 'interrupt-driven I/O'.",
  "Convert the decimal number 42 to binary.",
  "Convert the decimal number 150 to octal.",
  "Convert the decimal number 255 to hexadecimal.",
  "Convert the binary number 101101 to decimal.",
  "Convert the binary number 11011.101 to decimal.",
  "Convert the binary number 10110110 to octal.",
  "Convert the binary number 111100001111 to hexadecimal.",
  "Convert the octal number 72 to decimal.",
  "Convert the octal number 345 to binary.",
  "Convert the octal number 671 to hexadecimal.",
  "Convert the hexadecimal number A5 to decimal.",
  "Convert the hexadecimal number F3 to binary.",
  "Convert the hexadecimal number 1AF to octal.",
  "Convert the decimal number 0.625 to binary.",
  "Convert the binary number 0.1101 to decimal.",
  "Convert the decimal number 173.75 to binary.",
  "Convert the binary number 1101.101 to hexadecimal.",
  "Convert the octal number 52.3 to decimal.",
  "Convert the hexadecimal number 9.C to binary.",
  "Convert the decimal number 27 to hexadecimal.",
  "Convert the binary number 100101 to decimal.",
  "Convert the octal number 123 to binary.",
  "Convert the hexadecimal number D8 to decimal.",
  "Convert the decimal number 88 to octal.",
  "Convert the binary number 11111111 to hexadecimal.",
  "Convert the octal number 400 to decimal.",
  "Convert the hexadecimal number 2B to binary.",
  "Convert the decimal number 10.125 to binary.",
  "Convert the binary number 0.011 to decimal.",
  "Convert the decimal number 5.875 to binary.",
  "Convert the binary number 101010.11 to decimal.",
  "Convert the octal number 77.7 to decimal.",
  "Convert the hexadecimal number B.5 to decimal.",
  "Convert the decimal number 64 to binary.",
  "Convert the decimal number 100 to octal.",
  "Convert the decimal number 200 to hexadecimal.",
  "Convert the binary number 1100100 to decimal.",
  "Convert the binary number 10000000000 to octal.",
  "Convert the binary number 110100110101 to hexadecimal.",
  "Convert the octal number 177 to decimal.",
  "Convert the octal number 10 to binary.",
  "Convert the octal number 25 to hexadecimal.",
  "Convert the hexadecimal number 1A to decimal.",
  "Convert the hexadecimal number 7E to binary.",
  "Convert the hexadecimal number C3 to octal.",
  "Convert the decimal number 0.8125 to binary.",
  "Convert the binary number 0.1010 to decimal.",
  "Convert the decimal number 32.5 to binary.",
  "Convert the binary number 1110.01 to octal.",
  "Convert the octal number 12.4 to binary.",
  "Convert the decimal number -127 to an 8-bit binary representation using 2's complement.",
  "Convert the signed 8-bit binary number 11101100 (2's complement) to its decimal equivalent.",
  "Convert the decimal number 31.6875 to its binary representation.",
  "Convert the binary number 101101.0111 to its hexadecimal equivalent.",
  "Convert the hexadecimal number F.AC to its binary equivalent.",
  "Convert the octal number 67.54 to its hexadecimal equivalent.",
  "Convert the decimal number 25.125 to its IEEE 754 single-precision floating-point representation.",
  "Given a single-precision IEEE 754 floating-point number 0 10000000 00000000000000000000000, what is its decimal value?",
  "Explain the implications of a longer pipeline in terms of performance benefits and potential hazards.",
  "Analyze a scenario where a data hazard occurs in a 5-stage pipeline (IF, ID, EX, MEM, WB) and propose a solution using forwarding/bypassing.",
  "Describe the concept of 'structural hazards' in pipelining and provide an example of how they might be mitigated.",
  "Compare and contrast the roles of the 'Program Counter' and the 'Instruction Pointer' in different CPU architectures.",
  "Discuss the trade-offs between implementing a Control Unit using 'hardwired logic' versus 'microprogramming'.",
  "Design a simple 2-bit ripple counter using JK flip-flops and explain its operation.",
  "Using Boolean algebra theorems, simplify the expression F = A'B'C' + A'BC' + AB'C' + ABC'.",
  "Apply De Morgan's theorem to simplify the expression (A + B)' + (A'B)''.",
  "Explain how a 4-to-1 Multiplexer can be used to implement a Boolean function of three variables.",
  "Describe the working principle of a Full Adder and its importance in the ALU.",
  "Analyze the impact of cache line size on cache hit rate and external fragmentation within the cache.",
  "Given a main memory of 4K blocks and a cache of 128 blocks, describe the address format for a direct-mapped cache.",
  "Explain the process of a 'write miss' in a write-back cache policy, considering a dirty block replacement.",
  "In a virtual memory system with 4KB pages, calculate the physical address given a virtual address and page table entry.",
  "Discuss the phenomenon of 'Thrashing' in virtual memory and methods to prevent it.",
  "Explain the purpose of 'Page Replacement Algorithms' and describe a scenario where 'LRU' performs better than 'FIFO'.",
  "Differentiate between 'memory interleaving' and 'cache mapping techniques'.",
  "Describe how an 'Interrupt Controller' handles multiple simultaneous interrupt requests with different priorities.",
  "Compare 'isolated I/O' and 'memory-mapped I/O' in terms of address space utilization and instruction set impact.",
  "Explain the sequence of events during a 'DMA transfer' from a peripheral to main memory.",
  "What is the function of the 'Bus Master' and 'Bus Slave' in a bus architecture?",
  "Discuss various 'Bus Arbitration' schemes (e.g., Daisy Chaining, Polling, Independent Request) and their advantages/disadvantages.",
  "Explain the fundamental difference in data processing between a 'Combinational Logic Circuit' and a 'Sequential Logic Circuit'.",
  "Describe how a JK flip-flop can be configured to act as a T flip-flop.",
  "What is the role of the 'Barrel Shifter' in a CPU's Arithmetic Logic Unit?",
  "Explain the difference between 'arithmetic shift' and 'logical shift' operations.",
  "Discuss the challenges of designing a 'superscalar' processor.",
  "How does 'speculative execution' improve performance, and what are its potential risks?",
  "Explain the concept of 'branch prediction' and its impact on pipeline efficiency.",
  "Describe the primary functions of an 'I/O Processor' (IOP).",
  "What is the purpose of 'ECC (Error-Correcting Code) memory' and how does it generally work?",
  "Discuss the trade-offs between 'fixed-point' and 'floating-point' representations for numbers in terms of range, precision, and hardware complexity.",
  "Explain the 'signed-magnitude', '1's complement', and '2's complement' representations for the decimal number -50, using 8 bits.",
  "Convert the excess-3 code 0110 1001 to its decimal equivalent.",
  "Convert the BCD number 01010011 to its decimal equivalent.",
  "What are the advantages of using 'Gray code' in rotary encoders?",
  "Design a minimal 3-bit synchronous up/down counter.",
  "Explain how 'virtual memory' helps in memory protection.",
  "Discuss how 'Cache Coherence Protocols' ensure data consistency across multiple CPU cores.",
  "Describe the steps a CPU takes to handle an 'interrupt' from an I/O device.",
  "What is the 'Von Neumann Bottleneck' and how do modern architectures attempt to mitigate it?",
  "In a system with multi-level caches (L1, L2, L3), explain the typical characteristics (size, speed, associativity) of each level.",
  "Explain how a CPU handles division using repeated subtraction or multiplication by reciprocals.",
  "Describe the concept of 'overflow' and 'underflow' in integer arithmetic.",
  "How are arithmetic operations performed on floating-point numbers?",
  "What is the role of a 'guard bit' and 'round bit' in floating-point arithmetic?",
  "Explain the difference between 'normalized' and 'denormalized' floating-point numbers.",
  "How does error detection using 'checksums' work?",
  "Describe the principle of 'Cyclic Redundancy Check (CRC)' for error detection.",
  "What is the 'Hamming distance' and its significance in error correction?",
  "Design a simple 2-bit magnitude comparator circuit.",
  "Explain the function of a 'decoder' in memory addressing.",
  "Describe the operation of a 'priority encoder'.",
  "How can a 'multiplexer' be used for parallel-to-serial data conversion?",
  "What is a 'memory cell' and how does it store a single bit of information?",
  "Explain the organization of a 'RAM chip' with address lines and data lines.",
  "Describe the read and write cycles for a static RAM (SRAM).",
  "What is the refresh cycle in dynamic RAM (DRAM)?",
  "Differentiate between 'mask-programmed ROM', 'PROM', 'EPROM', and 'EEPROM'.",
  "Explain the concept of 'flash memory' and its applications.",
  "How does 'content-addressable memory (CAM)' work?",
  "Describe the role of 'control signals' in CPU operations.",
  "Explain the difference between 'micro-architecture' and 'instruction set architecture'.",
  "What is 'concurrency' in computer architecture?",
  "How does 'parallel processing' differ from 'pipelining'?",
  "Describe the concept of 'thread-level parallelism'.",
  "What is 'Instruction-Level Parallelism (ILP)'?",
  "Explain the role of 'hardware multithreading' in modern processors.",
  "What is a 'superscalar' processor and how does it achieve parallelism?",
  "How do 'VLIW (Very Long Instruction Word)' architectures work?",
  "What are 'SIMD (Single Instruction, Multiple Data)' instructions and their applications?",
  "Explain the concept of 'dataflow architecture'.",
  "What is the primary function of a 'Register Renaming' technique?",
  "How does 'Reorder Buffer' contribute to out-of-order execution?",
  "Describe the process of a 'Translation Lookaside Buffer (TLB) miss'.",
  "What is the purpose of 'Page Table Entry (PTE)' flags beyond valid/dirty bits?",
  "Explain the concept of 'Inverse Page Tables'.",
  "What are the challenges of implementing 'segmentation with paging'?",
  "Describe the different types of 'bus interfaces' (e.g., synchronous, asynchronous).",
  "What is 'bus sizing' and its importance?",
  "Explain 'bus buffering' and 'bus arbitration' in multi-master bus systems.",
  "What are 'programmed I/O' interrupts used for?",
  "Describe the stages of an 'interrupt handling routine'.",
  "What is 'Direct Memory Access (DMA)' and its advantages over programmed I/O?",
  "Explain the different types of 'DMA transfer modes' (e.g., burst mode, cycle stealing).",
  "What is the role of the 'I/O controller' or 'device controller'?",
  "How do 'channels' improve I/O operations in large systems?",
  "What is 'RAID' technology and its different levels?",
  "Explain the concept of 'fault tolerance' in computer systems.",
  "Describe 'redundancy' as a technique for improving reliability.",
  "What is 'temporal redundancy' versus 'spatial redundancy'?",
  "How is 'error detection' different from 'error correction'?"
]
}